### ISSUE TITLE
Add new solver to metaSMT

### ISSUE THREAD

**Issue by qingyangcx** [agra-uni-bremen/metaSMT#41]
Is metaSMT only support STP Z3 Booletor?I want to add some other solver to metaSMT,like dreal3,mathsat.
Could you give me some advise?Sincerely need your help!

**Comment by hoangmle** [comment]
I assume you want to use metaSMT with KLEE. In addition to STP, Z3 and Boolector, we do have support for CVC4 and Yices2. However, note that metaSMT only supports the QF_AUFBV theory.
Adding MathSat for QF_AUFBV is rather straight-forward, you can take a look at https://github.com/agra-uni-bremen/metaSMT/blob/development/src/metaSMT/backend/Z3_Backend.hpp for an example. Adding Dreal3 requires a lot of work and you can't use it with KLEE because it currently only supports QF_ABV.

**Comment by EvanNightWish** [comment]
hi, I want to use Yices2 in klee by metaSMT, but I only find the CVC4,hpp in metaSMT source code, so could I use the latest Yices2 through metaSMT now ? Sincerely need your help!

**Comment by hoangmle** [comment]
Hi @EvanNightWish, those changes are not yet upstream, you need to check out my fork https://github.com/hoangmle/metaSMT/tree/qf_abv

**Comment by EvanNightWish** [comment]
@hoangmle Very thanks for you. I download and install metaSMT with STP and Yices2 successfully, then I want to use metaSMT in klee as a core solver. But when I build klee with metaSMT, it occurs an error like this : 
"Linking CXX executable ../../bin/kleaver
/usr/bin/ld: _ZN3stp21GlobalParserInterfaceE: TLS definition in /klee/metaSMT/metaSMT_yices/metaSMT/deps/stp-2.3.1-basic/lib/libstp.so.2.1 section .tbss mismatches non-TLS definition in /usr/local/lib/libstp.a(Globals.cpp.o) section .bss
/klee/metaSMT/metaSMT_yices/metaSMT/deps/stp-2.3.1-basic/lib/libstp.so.2.1: error adding symbols: Bad value
collect2: error: ld returned 1 exit status"

Some people say this may be caused by the  latest gcc beause it cannot deal with the "extern" keyword. Have you ever encountered this question? Should I build the metaSMT with some changes? Thanks for your help!

**Comment by hoangmle** [comment]
I haven't seen this error before, which gcc version are you using? Do you really need to use STP via metaSMT? I would try to use Boolector and Yices2 via metaSMT and KLEE's STP directly

**Comment by EvanNightWish** [comment]
@hoangmle This is caused by the wrong version of STP. But I think I need to install STP in metaSMT because I meet the same problem in https://github.com/klee/klee/issues/805. I fix this problem via modifying the content of bootstrap.sh like that

> FREE="
  cvc4-1.5
  stp-2.3.1-basic
  yices-2.5.2
"

Or should I specify the path of STP when installing metaSMT?

**Comment by hoangmle** [comment]
@EvanNightWish Using stp-2.3.1 should be ok
